"""Validate the end-to-end assembly: captured landmarks -> pipeline -> BVH vs golden2.bvh.

Feeds the SAME landmarks the reference engine used (golden2 capture) so this isolates the solver
assembly (not detection). Reports per-BVH-joint rotation error on the solved bones; the
unsolved joints (head/neck/hands/fingers/shoulders) are identity here and are skipped.
"""

import json
import math
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from mocapy.vrm.skeleton import load_skeleton  # noqa: E402
from mocapy.export.bvh import build_hierarchy, write_bvh  # noqa: E402
from mocapy.pipeline import solve_sequence, vrm_to_mmd_from_hierarchy  # noqa: E402

from mocapy._paths import FIXTURES, ASSETS  # noqa: E402
# BVH joints we solve (others are identity in our output) and their channel kind.
SOLVED_JOINTS = [
    "hips", "spine", "chest",
    "leftUpperArm", "leftLowerArm", "rightUpperArm", "rightLowerArm",
    "leftUpperLeg", "leftLowerLeg", "leftFoot",
    "rightUpperLeg", "rightLowerLeg", "rightFoot",
]


def parse_motion(bvh_text):
    lines = bvh_text.replace("\r\n", "\n").split("\n")
    # joint order with channel counts
    joints = []
    for ln in lines:
        s = ln.strip()
        if s.startswith("ROOT ") or s.startswith("JOINT "):
            joints.append(s.split(None, 1)[1])
        elif s.startswith("CHANNELS"):
            n = int(s.split()[1])
            joints[-1] = (joints[-1], n)
        if s == "MOTION":
            break
    i = next(k for k, ln in enumerate(lines) if ln.strip() == "MOTION")
    frames = int(lines[i + 1].split(":")[1])
    rows = np.array([[float(x) for x in lines[i + 3 + r].split()] for r in range(frames)])
    # channel offsets per joint
    off = {}
    c = 0
    for name, n in joints:
        off[name] = (c, n)
        c += n
    return rows, off


def main() -> int:
    skel = load_skeleton(ASSETS / "cj.vrm")
    gj = json.loads((FIXTURES / "golden2.bvh.golden.json").read_text(encoding="utf-8"))
    lm = json.loads((FIXTURES / "golden2.bvh.landmarks.json").read_text(encoding="utf-8"))

    # frames_kp3 (world) + frames_px (2D screen) indexed by frame_count (last Me per frame)
    by_frame, by_px = {}, {}
    for c in lm:
        m = json.loads(c["m"]) if isinstance(c["m"], str) else c["m"]
        pose = m.get("posenet", {})
        by_frame[c["f"]] = pose.get("keypoints3D")
        kp2 = pose.get("keypoints")
        if kp2:
            by_px[c["f"]] = [[kp2[i]["position"]["x"], kp2[i]["position"]["y"],
                              kp2[i]["position"].get("z", 0.0)] for i in range(len(kp2))]
    n = max(by_frame) + 1
    frames = [by_frame.get(f) for f in range(n)]
    frames_px = [by_px.get(f) for f in range(n)]

    # the reference headless canvas is 1280x720 (electron_main: min(1280, workarea))
    bone_keys = solve_sequence(frames, frames_px=frames_px, frame_size=(1280, 720))
    _, order = build_hierarchy(skel)
    vrm_to_mmd = vrm_to_mmd_from_hierarchy(gj["hierarchy_list"], order)
    leg_scale = gj["left_leg_length"] / gj["model_para_left_leg_length"]
    pos_scale = gj["vrm_scale"] / gj["VRM_vrm_scale"]

    # Both BVHs get the the reference-style rest frame at index 0; actual mocap from frame 1.
    # (golden2.bvh was generated by an older the reference build that did NOT inject the rest
    # frame — its frame 0 is already mocap data — so for this comparison we still
    # opt out of the prepend on our side and align M[0:nf] with R[0:nf] directly.)
    mine_txt = write_bvh(skel, bone_keys, vrm_to_mmd, leg_scale=leg_scale,
                         pos_scale=pos_scale, prepend_rest_frame=False)
    ref_txt = (FIXTURES / "golden2.bvh").read_text(encoding="utf-8")

    M, offM = parse_motion(mine_txt)
    R, offR = parse_motion(ref_txt)
    # Skip the first frame (mocap warm-up: the OneEuro filters have no history
    # at f=0 so they pass the raw signal through unfiltered, which can land far
    # from the reference's filtered output).
    nf = min(M.shape[0], R.shape[0])
    print(f"frames: mine={M.shape[0]} ref={R.shape[0]}; comparing {nf - 1} (frame 1..)\n")
    # Arms' BVH lowerArm folds in the 手捩 grant (not yet solved); torso+legs are clean.
    torso_legs = [j for j in SOLVED_JOINTS if "Arm" not in j]
    arms = [j for j in SOLVED_JOINTS if "Arm" in j]
    print(f"{'joint':16} {'rot median':>11} {'rot p90':>9}")

    def joint_err(j):
        cM, nM = offM[j]; cR, nR = offR[j]
        err = np.abs(M[1:nf, cM + nM - 3: cM + nM] - R[1:nf, cR + nR - 3: cR + nR])
        err = np.minimum(err, 360 - err)
        return np.abs(err).max(axis=1)

    worst_tl = 0.0
    for j in torso_legs:
        e = joint_err(j)
        worst_tl = max(worst_tl, float(np.median(e)))
        print(f"{j:16} {np.median(e):10.3f}° {np.percentile(e,90):8.3f}°")
    print("  --- arms (BVH lowerArm = ひじ·手捩 twist-grant; residual = arm smoothing lag) ---")
    for j in arms:
        e = joint_err(j)
        print(f"{j:16} {np.median(e):10.3f}° {np.percentile(e,90):8.3f}°")
    print("  --- head/neck (50/50 split; Dt filter polish remains) ---")
    for j in ("neck", "head"):
        if j in offM and j in offR:
            e = joint_err(j)
            print(f"{j:16} {np.median(e):10.3f}° {np.percentile(e,90):8.3f}°")

    # root translation: hips position channels (0,1,2)
    hp_m = M[1:nf, 0:3]
    hp_r = R[1:nf, 0:3]
    perr = np.abs(hp_m - hp_r)
    rng = hp_r.max(axis=0) - hp_r.min(axis=0)
    print("\nroot translation (hips position):")
    print(f"  golden range x/y/z: {rng[0]:.1f}/{rng[1]:.1f}/{rng[2]:.1f}  "
          f"my abs err median x/y/z: {np.median(perr[:,0]):.2f}/{np.median(perr[:,1]):.2f}/{np.median(perr[:,2]):.2f}")
    moves = (M[:, 0].max() - M[:, 0].min()) > 1.0
    print(f"  hips translate (not locked): {moves}")

    print(f"\nworst torso+legs joint median: {worst_tl:.3f}°")
    # BVH per-channel YXZ-Euler decomposition amplifies sub-degree quaternion
    # errors into 3-4° per-channel medians (one MMD bone error of ~1° can show
    # up as 3° on the leg-bend axis). 4.0° here corresponds to ~1-1.5° MMD
    # quaternion error per the documented error table.
    ok = worst_tl < 4.0 and moves
    print("RESULT:", "PASS — torso+legs + root translation end-to-end" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
